
BigWigsDB = {
	["disabledModules"] = {
		["Default"] = {
			["Verteidiger des Anubisath"] = true,
			["Razuvious Assistant"] = true,
			["Thaddius"] = true,
			["Loatheb"] = true,
			["Ragnaros"] = true,
			["Ouro"] = true,
			["Schlachtwache Sartura"] = true,
			["Thaddius Arrows"] = true,
			["Majordomus Executus"] = true,
			["Healbot Assist"] = true,
			["Razorgore der Ungezähmte"] = true,
			["Hohepriester Thekal"] = true,
			["Heigan der Unreine"] = true,
			["Die Käferfamilie"] = true,
			["Azuregos"] = true,
			["Großwitwe Faerlina"] = true,
			["Jin'do der Verhexer"] = true,
			["C'Thun"] = true,
			["Onyxia"] = true,
			["Prinzessin Huhuran"] = true,
			["General Rajaxx"] = true,
			["Baron Geddon"] = true,
			["Hohepriesterin Mar'li"] = true,
			["Viscidus"] = true,
			["Hohepriester Venoxis"] = true,
			["Feuerschwinge"] = true,
			["Gothik der Seelenjäger"] = true,
			["Gehennas"] = true,
			["Vaelastrasz der Verdorbene"] = true,
			["Ossirian der Narbenlose"] = true,
			["Emeriss"] = true,
			["Schattenschwinge"] = true,
			["Flickwerk"] = true,
			["Saphiron"] = true,
			["Lord Kazzak"] = true,
			["Flammenmaul"] = true,
			["Fankriss der Unnachgiebige"] = true,
			["Shazzrah"] = true,
			["Kel'Thuzad"] = true,
			["Nefarian"] = true,
			["Die Zwillings-Imperatoren"] = true,
			["Brutwächter Dreschbringer"] = true,
			["Anub'Rekhan"] = true,
			["Buru der Verschlinger"] = true,
			["Der Prophet Skeram"] = true,
			["Instrukteur Razuvious"] = true,
			["Hohepriesterin Jeklik"] = true,
			["Lucifron"] = true,
			["Maexxna"] = true,
			["Gluth"] = true,
			["Blutfürst Mandokir"] = true,
			["Grobbulus"] = true,
			["Die Vier Reiter"] = true,
			["Magmadar"] = true,
			["Moam"] = true,
			["Hakkar"] = true,
			["Beschützer des Anubisath"] = true,
			["Ayamiss der Jäger"] = true,
			["Hohepriesterin Arlokk"] = true,
			["Chromaggus"] = true,
			["Noth der Seuchenfürst"] = true,
		},
	},
}
BigWigsFubarDB = {
	["profiles"] = {
		["Default"] = {
			["minimapPosition"] = 237.4824782421092,
			["detachedTooltip"] = {
			},
		},
	},
}
