
eCastingBar_Saved = {
	["Bärforceone - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 4,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 637,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 7,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 690,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellLength"] = -1,
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["Height"] = 30,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
	},
	["Synflix - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 8,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 654,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 8,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 702,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
	["Haeldeus - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 3,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 648,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 8,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 695,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
	["Synti - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 279,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 699,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 1,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 699,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
	["Thanagor - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 666,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 729,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 389,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 733,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
	["Ricky - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = -13,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 657,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = -13,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 700,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
	["Syllix - Nefarian"] = {
		["FontSize"] = 12,
		["MirrorUsePerlTexture"] = 1,
		["EnemyColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["Left"] = 26,
		["SuccessColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["FlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["ShowTime"] = 1,
		["ChannelColor"] = {
			[1] = 0.3,
			[2] = 0.3,
			[3] = 1,
			[4] = 1,
		},
		["MirrorHeight"] = 30,
		["MirrorLocked"] = 0,
		["Bottom"] = 659,
		["MirrorHideBorder"] = 0,
		["MirrorWidth"] = 264,
		["Width"] = 264,
		["HideBorder"] = 0,
		["MirrorFontSize"] = 12,
		["ExhaustionColor"] = {
			[1] = 1,
			[2] = 0.9,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellLength"] = -1,
		["MirrorLeft"] = 34,
		["ShowSpellRank"] = 0,
		["ShowDelay"] = 1,
		["MirrorBottom"] = 697,
		["Locked"] = 0,
		["SpellJustify"] = "Center",
		["UsePerlTexture"] = 1,
		["BreathColor"] = {
			[1] = 0,
			[2] = 0.5,
			[3] = 1,
			[4] = 1,
		},
		["Enabled"] = 1,
		["FriendColor"] = {
			[1] = 0,
			[2] = 0,
			[3] = 1,
			[4] = 1,
		},
		["UseFriendlyEnemy"] = 0,
		["SpellColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["TimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorShowTime"] = 1,
		["DelayColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["MirrorSpellJustify"] = "Center",
		["MirrorTimeColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MirrorFlashBorderColor"] = {
			[1] = 1,
			[2] = 0.88,
			[3] = 0.25,
			[4] = 1,
		},
		["MirrorEnabled"] = 1,
		["Height"] = 30,
		["FailedColor"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["FeignDeathColor"] = {
			[1] = 1,
			[2] = 0.7,
			[3] = 0,
			[4] = 1,
		},
		["SpellLength"] = -1,
	},
}
eCastingBar_Settings = {
}
