
QuestlogOptions = {
	["Synflix-Nefarian"] = {
		["LockTracker"] = 0,
		["AddNew"] = 0,
		["InfoOnQuestCompletion"] = 0,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
			["corner"] = "TOPRIGHT",
			["pointone"] = 1301.87917219435,
			["pointtwo"] = 499.6007479102057,
		},
		["TrackerSymbol"] = 0,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 0,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["HeaderList"] = {
		},
		["RemoveCompletedObjectives"] = 0,
		["ItemTooltip"] = 1,
		["MobTooltip"] = 1,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["AutoCompleteQuests"] = 0,
		["ShowZonesInTracker"] = 1,
	},
	["Ricky-Nefarian"] = {
		["LockTracker"] = 0,
		["AddNew"] = 0,
		["InfoOnQuestCompletion"] = 0,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
			["corner"] = "TOPRIGHT",
			["pointone"] = 1252.329783237754,
			["pointtwo"] = 525.7248572091537,
		},
		["TrackerSymbol"] = 0,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 0,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
			[1] = "Tanaris,44,Noch mehr W√ºstenl√§ufergerechtigkeit",
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["ShowZonesInTracker"] = 1,
		["AutoCompleteQuests"] = 0,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["MobTooltip"] = 1,
		["ItemTooltip"] = 1,
		["RemoveCompletedObjectives"] = 0,
		["HeaderList"] = {
		},
	},
	["Haeldeus-Nefarian"] = {
		["LockTracker"] = 0,
		["AddNew"] = 0,
		["InfoOnQuestCompletion"] = 0,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
		},
		["TrackerSymbol"] = 0,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 0,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["HeaderList"] = {
		},
		["RemoveCompletedObjectives"] = 0,
		["ItemTooltip"] = 1,
		["MobTooltip"] = 1,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["AutoCompleteQuests"] = 0,
		["ShowZonesInTracker"] = 1,
	},
	["B√§rforceone-Nefarian"] = {
		["LockTracker"] = 0,
		["AddNew"] = 0,
		["InfoOnQuestCompletion"] = 0,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
		},
		["TrackerSymbol"] = 0,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 0,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["ShowZonesInTracker"] = 1,
		["AutoCompleteQuests"] = 0,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["MobTooltip"] = 1,
		["ItemTooltip"] = 1,
		["RemoveCompletedObjectives"] = 0,
		["HeaderList"] = {
		},
	},
	["Synti-Nefarian"] = {
		["LockTracker"] = 0,
		["AddNew"] = 0,
		["InfoOnQuestCompletion"] = 0,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
		},
		["TrackerSymbol"] = 0,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 0,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["ShowZonesInTracker"] = 1,
		["AutoCompleteQuests"] = 0,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["MobTooltip"] = 1,
		["ItemTooltip"] = 1,
		["RemoveCompletedObjectives"] = 0,
		["HeaderList"] = {
		},
	},
}
QuestLevel_Quest2Level = {
	["Vernichtung der Bestie"] = "@x§<16§",
	["Ausrottung der Deviat"] = "@x§<21§",
	["Frischfleisch"] = "<44§",
	["Vorsha die Peitscherin"] = "@x§<25§",
	["T√∂tet Spitzhauer!"] = "<5§",
	["Galgars Kaktusapfel Surprise"] = "<3§",
	["Die Kraft des Feindes wird auf die Probe gestellt"] = "@x§<15§",
	["Deviatb√§lge"] = "@x§<17§",
	["Vergiftetes Wasser"] = "<5§",
	["Fremdartiges Ei"] = "<26§",
	["Ritus der Kraft"] = "<4§",
	["Die √ºberfallene Karawane"] = "<8§",
	["Die heilige Flamme"] = "<25§",
	["Piratenh√ºte Ahoy!"] = "<45§",
	["Noch mehr W√ºstenl√§ufergerechtigkeit"] = "<44§",
	["Raptorh√∂rner"] = "<18§",
	["R√§cht mein Dorf"] = "<18§",
	["Die Suche nach dem verloren gegangenen Ranzen"] = "@x§<16§",
	["Isha Awak"] = "<27§",
	["Minshinas Sch√§del"] = "<9§",
	["Das Ende der Unterbrechungen"] = "<15§",
	["Klaue von Scharfkralle"] = "<30§",
	["Trollgl√ºcksbringer"] = "<24§",
	["Venture Company-Bergbau"] = "<41§",
	["Margoz"] = "<12§",
	["Anf√ºhrer der Giftz√§hne"] = "@x§<22§",
	["Verog der Derwisch"] = "<18§",
	["Hamuul Runetotem"] = "<16§",
	["Vereitelung der Kolkaraggression"] = "<8§",
	["Wiederbeschaffung des verloren gegangenen Ranzens"] = "@x§<16§",
	["Beherrschen der Raptorenjagd"] = "@x§<43§",
	["Die Befehle des Admirals"] = "<7§",
	["Grubenratteneintopf"] = "<23§",
	["Spaltknochenhalskette"] = "<42§",
	["Das Buch von Ur"] = "@x§<26§",
	["Die Knochenh√∂hle"] = "<12§",
	["Ziz Fizziks"] = "<21§",
	["Die Berichte des Warsongklans"] = "<19§",
	["Befriedung der Zentauren"] = "<25§",
	["Die D√§monensaat"] = "<14§",
	["Beherrschen der Pantherjagd"] = "@x§<40§",
	["Nara Wildm√§hne"] = "<16§",
	["Kreischergeister"] = "<44§",
	["Die Horde braucht Euch!"] = "<60§",
	["Hart auf hart"] = "<24§",
	["Die verlorenen Seiten"] = "<30§",
	["Gestohlenes Silber"] = "<18§",
	["Armee des schwarzen Gro√üdrachen"] = "<43§",
	["Praktische Beute"] = "<8§",
	["Thazz'rils Hacke"] = "<4§",
	["Ritus der Weisheit"] = "<10§",
	["Ritus der Sicht"] = ">7§<6§",
	["Theramores Spione"] = "<35§",
	["Verborgene Feinde"] = "@§>16§<12§",
	["Windfuriengefahr"] = "<8§",
	["Mazzranache"] = "<8§",
	["Inmitten der Ruinen"] = "@x§<27§",
	["Windreiter"] = "<29§",
	["Eier der Kluftmoosspinnen"] = "<20§",
	["Mahren Himmelsdeuter"] = "<27§",
	["Die Jagd im Ashenvale"] = "<20§",
	["Riten der Erdenmutter"] = ">5§<3§",
	["Wenikee K√ºbelbolz"] = "<14§",
	["Vorbereitungen auf die Zeremonie"] = "<11§",
	["Die Kundschafter des Ashenvales"] = "<24§",
	["Eine unvollendete Aufgabe"] = "<5§",
	["√Ñrger in der Tiefe"] = "@x§<22§",
	["Aus den Wrackteilen geborgen..."] = "<8§",
	["√úbergriff"] = "<10§",
	["Ebenenschreiterbedrohung"] = "<12§",
	["Eine heilige Bestattung"] = "<10§",
	["Die B√ºrde eines Peons"] = "<5§",
	["Winterhufs√§uberung"] = "<6§",
	["Melor schickt Kunde"] = "<30§",
	["Dunkle St√ºrme"] = "<12§",
	["Die Gr√ºnen H√ºgel des Schlingendorntals"] = "<40§",
	["Sturzfliegerjagd"] = "<6§",
	["Die Kanonen von Northwatch"] = "<20§",
	["Gaunerei und Erpressung im S√ºdmeer"] = "<45§",
	["Sarkoth"] = "<5§",
	["Die Macht zu Zerst√∂ren..."] = "@x§<16§",
	["Satyrh√∂rner"] = "<26§",
	["√úble Familiare"] = "<4§",
	["Gemeinsame Nutzung des Landes"] = "<6§",
	["Des Minenarbeiters Verm√∂gen"] = "<18§",
	["Wind in der W√ºste"] = "<9§",
	["Echeyakee"] = "<16§",
	["Samophlang"] = "<14§",
	["Die brackige Oase"] = "<16§",
	["Zerbrecht ein paar Eier"] = "<8§",
	["Therzok"] = "<10§",
	["Ein geistvolles Getr√§nk"] = "<7§",
	["Raptorendiebe"] = "<13§",
	["Chens leeres F√§sschen"] = "<24§",
	["Vereitelung der Angriffe"] = "<12§",
	["Bericht an Orgnil"] = "<7§",
	["Freiwilliger der Horde"] = "<12§",
	["Schlangenflaum"] = "<18§",
	["S√ºdmeerfreibeuter"] = "<14§",
	["Sicherung der Linien"] = "<11§",
	["Nachschub des Warsongklans"] = "<27§",
	["Medaillon der Brennenden Klinge"] = "<5§",
	["Vernichtet die Verr√§ter"] = "<7§",
	["Mok'Thardins Verzauberung"] = "<41§",
	["Die Shattered Hand"] = "<13§",
	["√Ñrger auf den Docks"] = "<18§",
	["K√∂nig der F√§ulnisklauen"] = "@x§<30§",
	["Die vergessenen Teiche"] = "<13§",
	["Ganns Rekultivierung"] = "<23§",
	["Bericht erstatten in Sen'jin"] = "<5§",
	["Neeru Feuerklinge"] = "<12§",
	["Zalazane"] = "<10§",
	["Crossroadwehrpflicht"] = "<12§",
	["GESUCHT: Baron K√ºstenschipper"] = "<16§",
	["Totem der Donnerh√∂rner"] = "<7§",
	["Die Kampfeber"] = "<4§",
	["Faule Peons"] = "<4§",
	["Werftmeister Flunkerblick"] = "<11§",
	["Klugheitstr√§nke"] = "@x§<18§",
	["Zwergenbuddelei"] = "<8§",
	["Die Tr√§ne der Monde"] = "<30§",
	["Stich des Skorpiden"] = "<3§",
	["GESUCHT: Arnak Grimmtotem"] = "<29§",
	["Ak'Zeloth"] = "<12§",
	["Pilzsporen"] = "<15§",
	["Freiheit f√ºr Ruul"] = "<24§",
	["Die Truhe des Kapit√§ns"] = "@x§<51§",
	["Nachricht zum Freiwindposten"] = "<25§",
	["Stillstand am Steinkrallenpfad"] = "<25§",
}
