
FQD = {
	["AlwaysNotify"] = false,
	["Bärforceone"] = {
		["tQuests"] = {
			[1] = "Eine bescheidene Bitte",
			[2] = " ",
			[3] = " ",
			[4] = " ",
			[5] = " ",
		},
		["nQuests"] = 0,
		["Format"] = 1,
		["Tag"] = false,
	},
	["Color"] = true,
	["Haeldeus"] = {
		["tQuests"] = {
			[1] = "Zentaurenarmschienen",
			[2] = "Zentaurenarmschienen",
			[3] = "Anführer der Kolkar",
			[4] = "Anführer der Kolkar",
			[5] = " ",
		},
		["nQuests"] = 0,
		["Format"] = 1,
		["Tag"] = false,
	},
	["AutoComplete"] = false,
	["Lock"] = true,
	["Thanagor"] = {
		["tQuests"] = {
			[1] = "Koboldkerzen",
			[2] = "Tauschhandel mit Goldstaub",
			[3] = "Millys Ernte",
			[4] = " ",
			[5] = " ",
		},
		["nQuests"] = 2,
		["Format"] = 1,
		["Tag"] = false,
	},
	["NoDrag"] = false,
	["AllowRaid"] = false,
	["AutoAdd"] = true,
	["AutoNotify"] = false,
	["Syllix"] = {
		["tQuests"] = {
			[1] = "Südmeerfreibeuter",
			[2] = "Raptorendiebe",
			[3] = "Raptorendiebe",
			[4] = " ",
			[5] = " ",
		},
		["nQuests"] = 1,
		["Format"] = 1,
		["Tag"] = false,
	},
	["Synti"] = {
		["tQuests"] = {
			[1] = "Gemeinsame Nutzung des Landes",
			[2] = "Windfuriengefahr",
			[3] = "Vergiftetes Wasser",
			[4] = "Ritus der Sicht",
			[5] = " ",
		},
		["nQuests"] = 0,
		["Format"] = 2,
		["Tag"] = false,
	},
	["Synflix"] = {
		["tQuests"] = {
			[1] = "Galgars Kaktusapfel Surprise",
			[2] = " ",
			[3] = " ",
			[4] = " ",
			[5] = " ",
		},
		["nQuests"] = 1,
		["Format"] = 1,
		["Tag"] = false,
	},
	["Ricky"] = {
		["tQuests"] = {
			[1] = "Wüstenläufergerechtigkeit",
			[2] = "Wüstenläufergerechtigkeit",
			[3] = "Kojoten-Diebe",
			[4] = "Kreatur der Leere",
			[5] = " ",
		},
		["nQuests"] = 0,
		["Format"] = 1,
		["Tag"] = false,
	},
	["AllowGuild"] = false,
	["Detail"] = true,
}
