
GatherItems = {
	[1] = {
		[1] = {
			["trolltruhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 40.46,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 32.29,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 40.83,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 33.56,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 41.31,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 34.21,
				},
				[4] = {
					["gtype"] = 0,
					["x"] = 41.23,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 35.37,
				},
				[5] = {
					["gtype"] = 0,
					["x"] = 41.68,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 35.71,
				},
				[6] = {
					["gtype"] = 0,
					["x"] = 41.53,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 34.77,
				},
				[7] = {
					["gtype"] = 0,
					["x"] = 39.8,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 32.99,
				},
				[8] = {
					["gtype"] = 0,
					["x"] = 40.25,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 33.18,
				},
				[9] = {
					["gtype"] = 0,
					["x"] = 39.91,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 34.1,
				},
				[10] = {
					["gtype"] = 0,
					["x"] = 40.43,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 34.35,
				},
			},
			["lebenswurz"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 78.66,
					["count"] = 0,
					["icon"] = 12,
					["y"] = 53.97,
				},
			},
			["würgetang"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 78.33,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 53.48,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 78.40000000000001,
					["count"] = 3,
					["icon"] = 7,
					["y"] = 52.58,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 78.76000000000001,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 52.07,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 10.92,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 33.12,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 11.3,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 31.93,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 11.04,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 30.69,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 10.12,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 29.75,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 10.78,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 29.15,
				},
				[9] = {
					["gtype"] = 1,
					["x"] = 11.39,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 28.9,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 11.83,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 28.37,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 12.38,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 28.08,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 13.17,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 28.24,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 14.06,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 28.22,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 15.47,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 28.09,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 14.87,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 27.45,
				},
				[16] = {
					["gtype"] = 1,
					["x"] = 14.03,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 27.06,
				},
				[17] = {
					["gtype"] = 1,
					["x"] = 13.06,
					["count"] = 3,
					["icon"] = 7,
					["y"] = 27.07,
				},
				[18] = {
					["gtype"] = 1,
					["x"] = 12.39,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 26.39,
				},
				[19] = {
					["gtype"] = 1,
					["x"] = 11.77,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 25.96,
				},
				[20] = {
					["gtype"] = 1,
					["x"] = 12.38,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 25.15,
				},
				[21] = {
					["gtype"] = 1,
					["x"] = 13.22,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 25.52,
				},
				[22] = {
					["gtype"] = 1,
					["x"] = 13.41,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 26.17,
				},
				[23] = {
					["gtype"] = 1,
					["x"] = 13.9,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 25.78,
				},
				[24] = {
					["gtype"] = 1,
					["x"] = 13.05,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 24.83,
				},
				[25] = {
					["gtype"] = 1,
					["x"] = 13.82,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 24.13,
				},
				[26] = {
					["gtype"] = 1,
					["x"] = 14.54,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 22.97,
				},
				[27] = {
					["gtype"] = 1,
					["x"] = 14.65,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 21.81,
				},
				[28] = {
					["gtype"] = 1,
					["x"] = 14.65,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 20.86,
				},
				[29] = {
					["gtype"] = 1,
					["x"] = 13.9,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 20,
				},
				[30] = {
					["gtype"] = 1,
					["x"] = 13.94,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 19.13,
				},
				[31] = {
					["gtype"] = 1,
					["x"] = 14.4,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 18.2,
				},
			},
			["lila lotus"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 30.46,
					["count"] = 0,
					["icon"] = 18,
					["y"] = 45.37,
				},
			},
			["beulengras"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 75.97,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 67.18000000000001,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 71.44,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 72.13,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 75.3,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 73.78,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 13.33,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 27.23,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 13.19,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 24.47,
				},
			},
			["maguskönigskraut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 71.12000000000001,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 76.37000000000001,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 28.75,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 46.84,
				},
			},
			["königsblut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 72.56,
					["count"] = 1,
					["icon"] = 11,
					["y"] = 73.04000000000001,
				},
			},
		},
		[3] = {
			["vorratskisten des crossroads"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 59.34,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 24.83,
				},
			},
			["kasten mit verschiedenen ersatzteilen"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 48.58,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 84.15000000000001,
				},
			},
			["würgetang"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 63.28,
					["count"] = 0,
					["icon"] = 7,
					["y"] = 40.35,
				},
			},
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 62.74,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 49.68,
				},
			},
			["waffenkiste"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 49.21,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 83.81999999999999,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 51.46,
					["count"] = 5,
					["icon"] = 1,
					["y"] = 30.98,
				},
			},
			["friedensblume"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 57.94,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 35.85,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 53.67,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 26.53,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 59.22,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 26.16,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 57.98,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 24.61,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 48.61,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 37.5,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 45.77,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 41.98,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 53.32,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 21.16,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 64,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 48.29,
				},
				[9] = {
					["gtype"] = 1,
					["x"] = 46.14,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 29.98,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 46.26,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 58.44,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 47.74,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 74.86,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 46.07,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 60.21,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 43.44,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 60.6,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 44.51,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 62.54,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 45.07,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 77.34999999999999,
				},
			},
			["maguskönigskraut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 61.63,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 10.89,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 62.86,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 10.8,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 62.79,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 15.54,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 49.13,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 24.87,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 45.66,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 26.71,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 41.91,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 23.22,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 41.76,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 24.16,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 45.37,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 36.65,
				},
				[9] = {
					["gtype"] = 1,
					["x"] = 58.27,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 36.87,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 54.27,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 36.36,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 48.69,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 36.53,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 46.99,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 36.13,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 56.88,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 34.44,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 48.77,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 75.2,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 46.41,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 24.18,
				},
				[16] = {
					["gtype"] = 1,
					["x"] = 48.06,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 25.58,
				},
				[17] = {
					["gtype"] = 1,
					["x"] = 44.56,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 40.81,
				},
				[18] = {
					["gtype"] = 1,
					["x"] = 44.46,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 34.55,
				},
				[19] = {
					["gtype"] = 1,
					["x"] = 51.7,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 48.97,
				},
			},
			["beulengras"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 48,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 35.73,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 46.36,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 36.29,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 48.44,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 18.2,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 45.1,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 36.99,
				},
			},
			["erdwurzel"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 62.33,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 9.880000000000001,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 62.71,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 11.11,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 61.08,
					["count"] = 2,
					["icon"] = 3,
					["y"] = 17.64,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 60.81,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 18.25,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 60.38,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 19.56,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 59.07,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 20.52,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 43.82,
					["count"] = 3,
					["icon"] = 3,
					["y"] = 24.05,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 42.75,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 24.39,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 49.98,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 17.32,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 63.55,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 47.45,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 63.41,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 48.83,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 62.34,
					["count"] = 2,
					["icon"] = 3,
					["y"] = 49.79,
				},
				[16] = {
					["gtype"] = 1,
					["x"] = 64.2,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 49.43,
				},
			},
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 62.02,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 16.14,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 53.05,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 24.43,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 54.07,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 35.66,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 45.57,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 21.29,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 52.57,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 32.07,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 50.41,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 30.23,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 48.27,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 37.55,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 47.81,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 37.89,
				},
				[9] = {
					["gtype"] = 1,
					["x"] = 48.41,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 39.02,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 45.3,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 30.92,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 61.37,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 16.32,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 54.72,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 21.95,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 50.37,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 24.05,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 46.22,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 37.2,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 46.34,
					["count"] = 4,
					["icon"] = 2,
					["y"] = 38.07,
				},
				[16] = {
					["gtype"] = 1,
					["x"] = 45.41,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 36.64,
				},
			},
			["wilddornrose"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 46.35,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 36.22,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 56.44,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 33.94,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 59.04,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 36.96,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 59.38,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 38.31,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 56.23,
					["count"] = 1,
					["icon"] = 5,
					["y"] = 42.09,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 57.51,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 50.4,
				},
			},
		},
		[5] = {
			["robuste truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 54.26,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 28.14,
				},
			},
			["lebenswurz"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 71.90000000000001,
					["count"] = 0,
					["icon"] = 12,
					["y"] = 70,
				},
			},
			["riesenweichpanzermuschel"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 30.46,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 34.22,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 32.72,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 35.28,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 35.2,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 34.77,
				},
				[4] = {
					["gtype"] = 0,
					["x"] = 33.88,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 33.31,
				},
			},
		},
		[16] = {
			["eisenvorkommen"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 47.13,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 42.2,
				},
			},
			["dokumententruhe #1"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 31.83,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 32.63,
				},
			},
			["dokumententruhe #3"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 39.29,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 41.51,
				},
			},
			["dokumententruhe #2"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 33.75,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 39.89,
				},
			},
		},
		[14] = {
			["robuste truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 34.95,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 68.86,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 28.39,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 64.14,
				},
			},
		},
		[11] = {
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 31.4,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 41.99,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 35.52,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 62.39,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 31.03,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 60.73,
				},
			},
			["friedensblume"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 59.59,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 60.64,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 58.9,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 56.03,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 46.79,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 49,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 43.53,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 47.2,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 43.54,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 40.54,
				},
			},
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 62.37,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 60.85,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 60.81,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 61.38,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 58.25,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 59.04,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 58.39,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 58.15,
				},
			},
			["nahrungsmittelkiste"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 53.66,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 47.97,
				},
			},
			["erdwurzel"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 68.97,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 58.9,
				},
			},
			["kupfervorkommen"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 32.6,
					["count"] = 8,
					["icon"] = 1,
					["y"] = 36.16,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 33.67,
					["count"] = 6,
					["icon"] = 1,
					["y"] = 40.1,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 31.22,
					["count"] = 8,
					["icon"] = 1,
					["y"] = 42.45,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 32.54,
					["count"] = 3,
					["icon"] = 1,
					["y"] = 49,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 34.75,
					["count"] = 6,
					["icon"] = 1,
					["y"] = 63.57,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 44.91,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 55.68,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 49.44,
					["count"] = 4,
					["icon"] = 1,
					["y"] = 50.3,
				},
				[8] = {
					["gtype"] = 2,
					["x"] = 50.84,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 52.62,
				},
				[9] = {
					["gtype"] = 2,
					["x"] = 53.56,
					["count"] = 4,
					["icon"] = 1,
					["y"] = 52.12,
				},
				[10] = {
					["gtype"] = 2,
					["x"] = 57.28,
					["count"] = 3,
					["icon"] = 1,
					["y"] = 35.69,
				},
				[11] = {
					["gtype"] = 2,
					["x"] = 56.93,
					["count"] = 4,
					["icon"] = 1,
					["y"] = 29.6,
				},
			},
		},
		[7] = {
			["wasserfass"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 50.09,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 80.90000000000001,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 64.38,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 72.87000000000001,
				},
			},
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 40.06,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 40.45,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 51.62,
					["count"] = 4,
					["icon"] = 2,
					["y"] = 77.56999999999999,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 64.03,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 76.34999999999999,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 64.13,
					["count"] = 6,
					["icon"] = 2,
					["y"] = 75.13,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 64.55,
					["count"] = 4,
					["icon"] = 2,
					["y"] = 73.65000000000001,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 65.25,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 82.45,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 66.78,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 87.69,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 39.37,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 40.56,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 56.15,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 69,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 56.01,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 68.36,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 55.56,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 67.59,
				},
				[13] = {
					["gtype"] = 1,
					["x"] = 55.25,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 66.99,
				},
				[14] = {
					["gtype"] = 1,
					["x"] = 54.9,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 66.5,
				},
				[15] = {
					["gtype"] = 1,
					["x"] = 54.99,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 63.37,
				},
				[16] = {
					["gtype"] = 1,
					["x"] = 54.85,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 62.76,
				},
				[17] = {
					["gtype"] = 1,
					["x"] = 54.98,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 62.34,
				},
				[18] = {
					["gtype"] = 1,
					["x"] = 54.73,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 61.47,
				},
				[19] = {
					["gtype"] = 1,
					["x"] = 54.77,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 54.8,
				},
				[21] = {
					["gtype"] = 1,
					["x"] = 50.31,
					["count"] = 3,
					["icon"] = 2,
					["y"] = 47.15,
				},
				[22] = {
					["gtype"] = 1,
					["x"] = 49.81,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 46.08,
				},
				[23] = {
					["gtype"] = 1,
					["x"] = 47.61,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 48.06,
				},
				[24] = {
					["gtype"] = 1,
					["x"] = 47.78,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 47.47,
				},
				[25] = {
					["gtype"] = 1,
					["x"] = 47.6,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 49.42,
				},
				[26] = {
					["gtype"] = 1,
					["x"] = 46.89,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 48.77,
				},
				[28] = {
					["gtype"] = 1,
					["x"] = 52.78,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 10.46,
				},
				[29] = {
					["gtype"] = 1,
					["x"] = 51.65,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 58.58,
				},
				[30] = {
					["gtype"] = 1,
					["x"] = 51.76,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 59.45,
				},
				[31] = {
					["gtype"] = 1,
					["x"] = 56.03,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 66.8,
				},
			},
			["gnomenwerkzeugkasten"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 61.8,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 45.85,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 62.34,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 45.93,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 63.89,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 50.23,
				},
				[4] = {
					["gtype"] = 0,
					["x"] = 61.97,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 55.45,
				},
				[5] = {
					["gtype"] = 0,
					["x"] = 63.19,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 58.04,
				},
			},
			["friedensblume"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 53.92,
					["count"] = 4,
					["icon"] = 1,
					["y"] = 78.09999999999999,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 65.40000000000001,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 86.12000000000001,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 54.52,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 67.94,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 54.16,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 64.18000000000001,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 54.63,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 55.53,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 55.02,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 51.89,
				},
				[7] = {
					["gtype"] = 1,
					["x"] = 38.29,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 39.72,
				},
				[8] = {
					["gtype"] = 1,
					["x"] = 42.85,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 39.7,
				},
				[9] = {
					["oldicon"] = 1,
					["y"] = 22.31,
					["x"] = 45.37,
					["count"] = 1,
					["gtype"] = 1,
					["icon"] = 1,
					["oldgtype"] = 1,
				},
				[10] = {
					["gtype"] = 1,
					["x"] = 50.59,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 16.3,
				},
				[11] = {
					["gtype"] = 1,
					["x"] = 52.46,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 57.98,
				},
				[12] = {
					["gtype"] = 1,
					["x"] = 52.77,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 60.2,
				},
			},
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 47.81,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 77.18000000000001,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 67.05,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 86.74,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 43.26,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 39.43,
				},
				[4] = {
					["gtype"] = 0,
					["x"] = 47.45,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 30.98,
				},
				[5] = {
					["gtype"] = 0,
					["x"] = 53.02,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 24.88,
				},
				[6] = {
					["gtype"] = 0,
					["x"] = 63.2,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 56.87,
				},
			},
			["erdwurzel"] = {
				[3] = {
					["gtype"] = 1,
					["x"] = 41.04,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 16.33,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 48.02,
					["count"] = 0,
					["icon"] = 3,
					["y"] = 19.56,
				},
			},
			["maguskönigskraut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 48.5,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 34,
				},
			},
		},
	},
	[2] = {
		[1] = {
			["eisenvorkommen"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 41.14,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 71.5,
				},
			},
		},
		[2] = {
			["eisenvorkommen"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 57.52,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 49.28,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 79.23,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 37.09,
				},
			},
			["wildstahlblume"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 76.68000000000001,
					["count"] = 0,
					["icon"] = 9,
					["y"] = 32.46,
				},
			},
			["lebenswurz"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 67.3,
					["count"] = 0,
					["icon"] = 12,
					["y"] = 62.27,
				},
			},
			["fass mit süßem nektar"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 35.44,
					["count"] = 1,
					["icon"] = 6,
					["y"] = 43.88,
				},
			},
			["geringe blutsteinablagerung"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 85.06999999999999,
					["count"] = 0,
					["y"] = 29.4,
				},
			},
			["blassblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 22.27,
					["count"] = 0,
					["icon"] = 13,
					["y"] = 36.54,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 65.79000000000001,
					["count"] = 0,
					["icon"] = 13,
					["y"] = 42.22,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 69.78,
					["count"] = 0,
					["icon"] = 13,
					["y"] = 32.88,
				},
			},
		},
		[24] = {
			["königsblut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 53.59,
					["count"] = 0,
					["icon"] = 11,
					["y"] = 19.46,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 49.81,
					["count"] = 0,
					["icon"] = 11,
					["y"] = 33.57,
				},
			},
			["feuerblüte"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 21.96,
					["count"] = 0,
					["icon"] = 17,
					["y"] = 46.48,
				},
			},
		},
		[13] = {
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 65.20999999999999,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 23.19,
				},
			},
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 62.09,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 11.42,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 57.11,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 10.91,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 44.43,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 31.22,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 41.96,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 31.1,
				},
			},
			["friedensblume"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 55.19,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 63.11,
				},
			},
		},
		[16] = {
			["robuste truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 54.99,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 29.81,
				},
			},
		},
		[17] = {
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 31.69,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 46.02,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 49.2,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 33.59,
				},
				[3] = {
					["gtype"] = 0,
					["x"] = 50.97,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 67.41,
				},
			},
			["perrines truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 51.08,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 67.59999999999999,
				},
			},
			["nahrungsmittelkiste"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 79.56,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 55.36,
				},
			},
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 57.97,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 38.68,
				},
			},
		},
		[9] = {
			["silberblatt"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 30.94,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 43.24,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 46.57,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 79.36,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 47.65,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 80.12000000000001,
				},
			},
		},
		[20] = {
			["robuste truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 79.24,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 39.45,
				},
				[2] = {
					["gtype"] = 0,
					["x"] = 27.96,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 72.93000000000001,
				},
			},
			["lebenswurz"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 66.31999999999999,
					["count"] = 0,
					["icon"] = 12,
					["y"] = 38.78,
				},
			},
			["maguskönigskraut"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 43.73,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 53.84,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 43.95,
					["count"] = 0,
					["icon"] = 4,
					["y"] = 55.52,
				},
			},
			["wilddornrose"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 32.89,
					["count"] = 0,
					["icon"] = 5,
					["y"] = 67.19,
				},
			},
		},
		[21] = {
			["ramponierte truhe"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 49.16,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 28.29,
				},
			},
		},
		[11] = {
			["nahrungsmittelkiste"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 26.73,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 19.78,
				},
			},
		},
		[18] = {
			["truhe mit verwahrungskästen"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 85.26000000000001,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 10.33,
				},
			},
		},
	},
}
GatherConfig = {
	["HideOnClick"] = 0,
	["minderTime"] = 5,
	["maxDist"] = 20,
	["users"] = {
		["Bärforceone"] = {
			["filterRecording"] = {
			},
			["filters"] = {
			},
		},
		["Ricky"] = {
			["filterRecording"] = {
			},
			["filters"] = {
				["herbs"] = "on",
			},
		},
		["Synflix"] = {
			["filterRecording"] = {
			},
			["filters"] = {
			},
		},
		["Synti"] = {
			["filterRecording"] = {
			},
			["filters"] = {
			},
		},
		["Syllix"] = {
			["filterRecording"] = {
			},
			["filters"] = {
			},
		},
		["Thanagor"] = {
			["filterRecording"] = {
			},
			["filters"] = {
			},
		},
		["Haeldeus"] = {
			["interested"] = {
				[1] = {
					["sonnengras"] = true,
					["lebenswurz"] = true,
					["würgetang"] = true,
					["schwarzer lotus"] = true,
					["königsblut"] = true,
					["bergsilberweisling"] = true,
					["golddorn"] = true,
					["eiskappe"] = true,
					["wildstahlblume"] = true,
					["maguskönigskraut"] = true,
					["traumblatt"] = true,
					["wilddornrose"] = true,
					["goldener sansam"] = true,
					["grabmoos"] = true,
					["silberblatt"] = true,
					["geisterpilz"] = true,
					["khadgars schnurrbart"] = true,
					["arthas’ tränen"] = true,
					["lila lotus"] = true,
					["blassblatt"] = true,
					["beulengras"] = true,
					["friedensblume"] = true,
					["pestblüte"] = true,
					["winterbiss"] = true,
					["blindkraut"] = true,
					["erdwurzel"] = true,
					["gromsblut"] = true,
					["feuerblüte"] = true,
				},
				[2] = {
					["zinn"] = true,
					["thorium (reiches)"] = true,
					["dunkeleisen"] = true,
					["kupfer"] = true,
					["mithril"] = true,
					["thorium"] = true,
					["eisen"] = true,
				},
				[0] = {
					["fass"] = true,
					["tonne"] = true,
					["un'Goro erde"] = true,
					["windblüte"] = true,
					["schwimmende trümmer"] = true,
					["kasten"] = true,
					["schließkiste"] = true,
					["peitscherwurzel"] = true,
					["truhe"] = true,
					["blutblüte"] = true,
					["kiste"] = true,
					["schwarm"] = true,
					["stelle mit elementarwasser"] = true,
					["liedblume"] = true,
					["schalentierfalle"] = true,
					["blut von helden"] = true,
					["nachtdrache"] = true,
					["muschel"] = true,
					["machtkristall"] = true,
				},
			},
			["filterRecording"] = {
			},
			["filters"] = {
				["herbs"] = "on",
			},
		},
	},
	["NoIconOnMinDist"] = 0,
	["HideOnButton"] = 0,
	["fadeDist"] = 40,
	["HideIcon"] = 0,
	["alphaUnderMinIcon"] = 100,
	["number"] = 10,
	["HideMiniNotes"] = 0,
	["miniIconDist"] = 40,
	["ShowOnClick"] = 0,
	["mapMinder"] = false,
	["ShowOnButton"] = 0,
	["showWorldMapFilters"] = 0,
	["disableWMFreezeWorkaround"] = 1,
	["Radius"] = 80,
	["iconSet"] = "shaded",
	["logInfo"] = "on",
	["useMainmap"] = true,
	["Position"] = 12,
	["ToggleWorldNotes"] = 0,
	["Version"] = "2.2.3.1",
	["useMinimapText"] = "on",
	["IconSize"] = 12,
	["rareOre"] = 0,
	["filter"] = "all",
	["fadePerc"] = 80,
	["HideOnMouse"] = 1,
	["ShowOnMouse"] = 1,
	["useMinimap"] = true,
}
