
RecipeRadar_SkillDB = {
	["Nefarian"] = {
		["Bärforceone"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
			},
			["Factions"] = {
			},
		},
		["Ricky"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Schneiderei"] = {
					["Recipes"] = {
					},
					["Rank"] = 171,
				},
				["Verzauberkunst"] = {
					["Recipes"] = {
						["Umhang - Schwacher Schutz"] = 1,
						["Umhang - Geringer Schutz"] = 1,
						["Runenverzierte Goldrute"] = 1,
						["Runenverzierte Kupferrute"] = 1,
						["Zweihandwaffe - Geringer Einschlag"] = 1,
						["Armschiene - Schwache Gesundheit"] = 1,
						["Brust - Geringe Gesundheit"] = 1,
						["Stiefel - Schwache Ausdauer"] = 1,
						["Schwaches Zauberöl"] = 1,
						["Brust - Schwache Werte"] = 1,
						["Schwaches Manaöl"] = 1,
						["Armschiene - Schwache Stärke"] = 1,
						["Brust - Mana"] = 1,
						["Brust - Schwache Gesundheit"] = 1,
						["Umhang - Geringer Feuerwiderstand"] = 1,
						["Umhang - Schwache Beweglichkeit"] = 1,
						["Armschiene - Schwache Beweglichkeit"] = 1,
						["Schild - Schwache Ausdauer"] = 1,
						["Waffe - Geringes Schlagen"] = 1,
						["Runenverzierte Silberrute"] = 1,
						["Armschiene - Schwache Abwehr"] = 1,
						["Brust - Schwaches Mana"] = 1,
						["Umhang - Schwacher Widerstand"] = 1,
						["Armschiene - Schwache Ausdauer"] = 1,
						["Brust - Schwache Absorption"] = 1,
						["Geringer Magiezauberstab"] = 1,
						["Stiefel - Schwache Beweglichkeit"] = 1,
						["Waffe - Schwaches Schlagen"] = 1,
						["Brust - Geringe Absorption"] = 1,
						["Armschiene - Geringe Stärke"] = 1,
						["Brust - Gesundheit"] = 1,
						["Großer Magiezauberstab"] = 1,
						["Zweihandwaffe - Schwacher Einschlag"] = 1,
						["Armschiene - Geringe Ausdauer"] = 1,
						["Schild - Geringe Willenskraft"] = 1,
					},
					["Rank"] = 165,
				},
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
				["Erste Hilfe"] = {
					["Recipes"] = {
						["Leinenverband"] = 1,
						["Schwerer Leinenverband"] = 1,
					},
					["Rank"] = 53,
				},
			},
			["Factions"] = {
				["Argentumdämmerung"] = 4,
				["Zirkel des Cenarius"] = 4,
			},
		},
		["Synflix"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Kochkunst"] = {
					["Recipes"] = {
						["Gewürztes Wolfsfleisch"] = 1,
						["Geröstetes Eberfleisch"] = 1,
						["Kräutergebackenes Ei"] = 1,
						["Verkohltes Wolfsfleisch"] = 1,
					},
					["Rank"] = 10,
				},
				["Lederverarbeitung"] = {
					["Recipes"] = {
					},
					["Rank"] = 37,
				},
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
				["Erste Hilfe"] = {
					["Recipes"] = {
						["Schwerer Leinenverband"] = 1,
						["Leinenverband"] = 1,
					},
					["Rank"] = 41,
				},
			},
			["Factions"] = {
			},
		},
		["Synti"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Kochkunst"] = {
					["Recipes"] = {
						["Geröstetes Eberfleisch"] = 1,
						["Verkohltes Wolfsfleisch"] = 1,
						["Kräutergebackenes Ei"] = 1,
					},
					["Rank"] = 1,
				},
				["Bergbau"] = {
					["Recipes"] = {
						["Kupfer verhütten"] = 1,
					},
					["Rank"] = 44,
				},
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
				["Schmiedekunst"] = {
					["Recipes"] = {
						["Kupferne Kettenstiefel"] = 1,
						["Kupferarmschienen"] = 1,
						["Rauer Schleifstein"] = 1,
						["Kupferstreitkolben"] = 1,
						["Kupferkurzschwert"] = 1,
						["Raue Kupferweste"] = 1,
						["Rauer Gewichtsstein"] = 1,
						["Kupferaxt"] = 1,
						["Kupferdolch"] = 1,
						["Kupferclaymore"] = 1,
						["Rauer Wetzstein"] = 1,
					},
					["Rank"] = 32,
				},
			},
			["Factions"] = {
			},
		},
		["Syllix"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
				["Alchimie"] = {
					["Recipes"] = {
						["Verfärbter Heiltrank"] = 1,
						["Elixier der Wasseratmung"] = 1,
						["Elixier der schwachen Verteidigung"] = 1,
						["Schwacher Trollbluttrank"] = 1,
						["Elixier der Weisheit"] = 1,
						["Schwacher Heiltrank"] = 1,
						["Schwarzmaulöl"] = 1,
						["Geringer Heiltrank"] = 1,
						["Elixier der Löwenstärke"] = 1,
						["Schwacher Verjüngungstrank"] = 1,
						["Schwacher Manatrank"] = 1,
						["Elixier der schwachen Seelenstärke"] = 1,
						["Wuttrank"] = 1,
					},
					["Rank"] = 94,
				},
			},
			["Factions"] = {
			},
		},
		["Thanagor"] = {
			["Team"] = "Alliance",
			["Professions"] = {
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 0,
				},
			},
			["Factions"] = {
			},
		},
		["Haeldeus"] = {
			["Team"] = "Horde",
			["Professions"] = {
				["Kochkunst"] = {
					["Recipes"] = {
						["Expertenkochbuch"] = 1,
						["Krebsküchlein"] = 1,
						["Kräutergebackenes Ei"] = 1,
						["Gewürztes Wolfsfleisch"] = 1,
						["Verkohltes Wolfsfleisch"] = 1,
						["Geröstetes Eberfleisch"] = 1,
						["Trockene Schweinerippchen"] = 1,
						["Kojotensteak"] = 1,
					},
					["Rank"] = 126,
				},
				["Alchimie"] = {
					["Recipes"] = {
						["Elixier der schwachen Beweglichkeit"] = 1,
						["Geringer Manatrank"] = 1,
						["Elixier der schwachen Verteidigung"] = 1,
						["Schwacher Verjüngungstrank"] = 1,
						["Elixier der schwachen Seelenstärke"] = 1,
						["Elixier der Löwenstärke"] = 1,
						["Schwacher Trollbluttrank"] = 1,
						["Elixier der Weisheit"] = 1,
						["Starker Trollbluttrank"] = 1,
						["Elixier der Verteidigung"] = 1,
						["Schwacher Manatrank"] = 1,
						["Schwacher Heiltrank"] = 1,
						["Wuttrank"] = 1,
						["Geringer Heiltrank"] = 1,
						["Heiltrank"] = 1,
						["Hurtigkeitstrank"] = 1,
						["Schattenschutztrank"] = 1,
					},
					["Rank"] = 155,
				},
				["Angeln"] = {
					["Recipes"] = {
					},
					["Rank"] = 107,
				},
				["Erste Hilfe"] = {
					["Recipes"] = {
					},
					["Rank"] = 125,
				},
			},
			["Factions"] = {
			},
		},
	},
}
RecipeRadar_NameCache = {
	[18648] = "Bauplan: Grünes Feuerwerk",
	[6346] = "Formel: Brust - Geringes Mana",
	[6349] = "Formel: Zweihandwaffe - Geringe Intelligenz",
	[10858] = "Pläne: Robuster Eisenschlägel",
	[16767] = "Rezept: Muschelsuppe à la Undermine",
	[7114] = "Muster: Azurblaue Seidenhandschuhe",
	[16072] = "Expertenkochbuch",
	[19446] = "Formel: Armschiene - Manaregeneration",
	[21099] = "Rezept: Geräucherter Weisenfisch",
	[7561] = "Bauplan: Goblinüberbrückungskabel",
	[3734] = "Rezept: Großes Bärensteak",
	[5787] = "Muster: Murlocschuppenbrustplatte",
	[5788] = "Muster: Dicke Murlocrüstung",
	[22774] = "Muster: Sylvanweste",
	[16217] = "Formel: Schild - Große Ausdauer",
	[20752] = "Formel: Schwaches Manaöl",
	[20758] = "Formel: Schwaches Zauberöl",
	[19216] = "Muster: Argentumstiefel",
	[5489] = "Rezept: Mageres Wildbret",
	[12164] = "Pläne: Massive Eisenaxt",
	[13308] = "Bauplan: Eisdeflektor",
	[20014] = "Rezept: Mächtiges Trollblutelixier",
	[6369] = "Rezept: Steinschuppenkabeljau",
	[6275] = "Muster: Große Adeptenrobe",
	[19766] = "Muster: Blutrebenstiefel",
	[6053] = "Rezept: Heiligschutztrank",
	[6326] = "Rezept: Glitschhautmakrele",
	[6054] = "Rezept: Schattenschutztrank",
	[5483] = "Rezept: Skorpid Surprise",
	[16111] = "Rezept: Gewürzter Chilikrebs",
	[5484] = "Rezept: Geröstetes Kodofleisch",
	[6056] = "Rezept: Frostschutztrank",
	[4609] = "Rezept: Gegrillter Bussardflügel",
	[6057] = "Rezept: Naturschutztrank",
	[5486] = "Rezept: Schreitereintopf",
	[12240] = "Rezept: Schwerer Kodoeintopf",
	[18647] = "Bauplan: Rotes Feuerwerk",
	[11039] = "Formel: Umhang - Schwache Beweglichkeit",
	[6377] = "Formel: Stiefel - Schwache Beweglichkeit",
	[12239] = "Rezept: Drachenodemchili",
	[15741] = "Muster: Sturmschleierhose",
	[13310] = "Bauplan: Genaues Zielfernrohr",
	[13501] = "Rezept: Erheblicher Manatrank",
	[5488] = "Rezept: Knuspriger Donnerechsenschwanz",
	[11163] = "Formel: Armschiene - Geringe Abwehr",
	[3682] = "Rezept: Seltsam schmeckendes Omelett",
	[5786] = "Muster: Murlocschuppengürtel",
	[22307] = "Muster: Verzauberter Magiestoffbeutel",
	[19765] = "Muster: Blutrebengamaschen",
	[12231] = "Rezept: Dschungeleintopf",
	[12703] = "Pläne: Sturmstulpen",
	[6274] = "Muster: Blauer Overall",
	[21219] = "Rezept: Weisenfisch Supreme",
	[18046] = "Rezept: Zartes Wolfsteak",
	[20013] = "Rezept: Trank der lebhaften Aktion",
	[6068] = "Rezept: Schattenöl",
	[12228] = "Rezept: Gerösteter Raptor",
	[6272] = "Muster: Blaue Leinenrobe",
	[4355] = "Muster: Eisiger Umhang",
	[6368] = "Rezept: Regenbogenflossenthunfisch",
	[3735] = "Rezept: Scharfe Löwenkoteletts",
	[7087] = "Muster: Purpurroter Seidenumhang",
	[22773] = "Muster: Sylvankrone",
	[13478] = "Rezept: Elixier der überragenden Verteidigung",
	[10318] = "Muster: Admiralshut",
	[10317] = "Muster: Rosa Magiestoffhemd",
	[6328] = "Rezept: Langzahniger Matschschnapper",
	[19217] = "Muster: Argentumschultern",
	[14627] = "Muster: Hellgelbes Hemd",
	[17062] = "Rezept: Mithrilkopfforelle",
	[10311] = "Muster: Orangefarbenes Kampfhemd",
	[6330] = "Rezept: Stoppelfühlerwels",
	[14630] = "Muster: Verzauberergugel",
	[20753] = "Formel: Geringes Zauberöl",
	[10314] = "Muster: Lavendelfarbenes Magiestoffhemd",
	[20757] = "Formel: Hervorragendes Manaöl",
	[14634] = "Rezept: Frostöl",
	[20761] = "Rezept: Elementarfeuer transmutieren",
	[18731] = "Muster: Schwerer Lederball",
	[6270] = "Muster: Blaue Leinenweste",
	[6325] = "Rezept: Glänzender Kleinfisch",
	[10321] = "Muster: Smokinghemd",
	[12227] = "Rezept: Mageres Wolfsteak",
	[10323] = "Muster: Smokinghose",
	[12229] = "Rezept: Scharfe Wolfrippchen",
	[10325] = "Muster: Weißes Hochzeitskleid",
	[10326] = "Muster: Smokingjacke",
	[12232] = "Rezept: Aas Surprise",
	[5640] = "Rezept: Wuttrank",
	[12233] = "Rezept: Eigenartiger Eintopf",
	[6401] = "Muster: Dunkles Seidenhemd",
	[6055] = "Rezept: Feuerschutztrank",
	[5642] = "Rezept: Trank der freien Aktion",
	[6892] = "Rezept: Geräuchertes Bärenfleisch",
	[5643] = "Rezept: Großer Wuttrank",
	[6342] = "Formel: Brust - Schwaches Mana",
	[5771] = "Muster: Rote Leinentasche",
	[7362] = "Muster: Irdene Lederschultern",
	[5772] = "Muster: Rote Wolltasche",
	[11101] = "Formel: Armschiene - Geringe Stärke",
	[19447] = "Formel: Armschiene - Heilkraft",
}
