
SCT_CONFIG = {
	["currentProfile"] = {
		["Thanagor von Nefarian"] = "char",
		["Ricky von Nefarian"] = "char",
		["Bärforceone von Nefarian"] = "char",
		["Synti von Nefarian"] = "char",
		["Synflix von Nefarian"] = "char",
		["Haeldeus von Nefarian"] = "char",
		["Syllix von Nefarian"] = "char",
	},
	["profiles"] = {
		["char/Bärforceone von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["r"] = 0.6,
					["g"] = 0.6,
					["b"] = 0,
				},
				["SCTD_SHOWPERIODIC"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["SCTD_SHOWSPELL"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["r"] = 0.2,
					["g"] = 0.4,
					["b"] = 0.6,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_SHOWCOLORCRIT"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_TARGET"] = false,
		},
		["char/Synti von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["r"] = 0.6,
					["g"] = 0.6,
					["b"] = 0,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["r"] = 0.2,
					["g"] = 0.4,
					["b"] = 0.6,
				},
				["SCTD_SHOWSPELL"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["SCTD_SHOWPERIODIC"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_TARGET"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_SHOWCOLORCRIT"] = false,
		},
		["char/Haeldeus von Nefarian"] = {
			["SCTD_DMGFONT"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["COLORS"] = {
				["SCTD_SHOWPET"] = {
					["b"] = 0,
					["g"] = 0.6,
					["r"] = 0.6,
				},
				["SCTD_SHOWPERIODIC"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWSPELL"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWMELEE"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["b"] = 0.6,
					["g"] = 0.4,
					["r"] = 0.2,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_SHOWCOLORCRIT"] = false,
			["SCTD_SHOWPET"] = 1,
			["SCTD_ENABLED"] = 1,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWDMGTYPE"] = false,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_TARGET"] = false,
		},
		["char/Thanagor von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["b"] = 0,
					["g"] = 0.6,
					["r"] = 0.6,
				},
				["SCTD_SHOWPERIODIC"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWSPELL"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["b"] = 0.6,
					["g"] = 0.4,
					["r"] = 0.2,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_SHOWCOLORCRIT"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_TARGET"] = false,
		},
		["char/Synflix von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWSPELL"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPERIODIC"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["b"] = 0,
					["g"] = 0.6,
					["r"] = 0.6,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["b"] = 0.6,
					["g"] = 0.4,
					["r"] = 0.2,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_SHOWCOLORCRIT"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_TARGET"] = false,
		},
		["char/Syllix von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["b"] = 0,
					["g"] = 0.6,
					["r"] = 0.6,
				},
				["SCTD_SHOWPERIODIC"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWSPELL"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["b"] = 0.6,
					["g"] = 0.4,
					["r"] = 0.2,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_SHOWCOLORCRIT"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_TARGET"] = false,
		},
		["char/Ricky von Nefarian"] = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["SCTD_DMGFONT"] = 1,
			["SCTD_ENABLED"] = 1,
			["SCTD_SPELLCOLOR"] = false,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWSPELL"] = 1,
			["FRAMESDATA"] = {
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 24,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 210,
					["XOFFSET"] = 0,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPET"] = {
					["b"] = 0,
					["g"] = 0.6,
					["r"] = 0.6,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["b"] = 0.6,
					["g"] = 0.4,
					["r"] = 0.2,
				},
				["SCTD_SHOWSPELL"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["SCTD_SHOWPERIODIC"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
			},
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_USESCT"] = 1,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["SCTD_TARGET"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_SHOWCOLORCRIT"] = false,
		},
	},
	["chars"] = {
		["Thanagor von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Ricky von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Bärforceone von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Synti von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Synflix von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Haeldeus von Nefarian"] = {
			["notFirstTime"] = true,
		},
		["Syllix von Nefarian"] = {
			["notFirstTime"] = true,
		},
	},
}
