
TitanAllPlayedSettings = {
	["playerOptions"] = {
		["hideIfSixty"] = false,
		["showServerTotals"] = true,
		["listScope"] = "allServers",
		["showServerGoldTotals"] = false,
		["showFullyRested"] = true,
		["showGold"] = true,
		["showCurrentOnlyLabel"] = false,
		["showRested"] = true,
		["colorRested"] = false,
		["timeBar"] = false,
		["timeServer"] = false,
		["timeGrand"] = false,
		["showLabelValue"] = true,
		["timeLink"] = false,
		["timeChar"] = false,
		["showLevel"] = true,
	},
}
TitanAllPlayedCharacters = {
	["Nefarian"] = {
		[1] = "Synti",
		["Bärforceone"] = {
			["coin"] = 1700,
			["isResting"] = 1,
			["lastUpdate"] = 1445895490,
			[3] = 1,
			["maxRested"] = 6750,
			["secondsPlayed"] = 5176,
			["faction"] = "Horde",
			["name"] = "Bärforceone",
			["level"] = 7,
			["rested"] = 0,
			["realm"] = "Nefarian",
		},
		["Ricky"] = {
			["coin"] = 248564,
			["isResting"] = 1,
			["lastUpdate"] = 1439291119,
			[3] = 1,
			["maxRested"] = 136050,
			["secondsPlayed"] = 309042,
			["faction"] = "Horde",
			["name"] = "Ricky",
			["level"] = 40,
			["rested"] = 136050,
			["realm"] = "Nefarian",
		},
		["Synflix"] = {
			["coin"] = 16800,
			["isResting"] = 1,
			["lastUpdate"] = 1441403657,
			[3] = 1,
			["maxRested"] = 24000,
			["secondsPlayed"] = 43046,
			["faction"] = "Horde",
			["name"] = "Synflix",
			["level"] = 16,
			["rested"] = 0,
			["realm"] = "Nefarian",
		},
		["Synti"] = {
			[2] = "Allgemein",
			[3] = 1,
			["coin"] = 48122,
			["isResting"] = 1,
			["lastUpdate"] = 1439291295,
			["maxRested"] = 11400,
			["name"] = "Synti",
			["faction"] = "Horde",
			["secondsPlayed"] = 19591,
			["level"] = 10,
			["rested"] = 11400,
			["realm"] = "Nefarian",
		},
		["Syllix"] = {
			["coin"] = 4709,
			["lastUpdate"] = 1436366679,
			[3] = 1,
			["maxRested"] = 29100,
			["secondsPlayed"] = 27059,
			["faction"] = "Horde",
			["name"] = "Syllix",
			["level"] = 18,
			["rested"] = 25158,
			["realm"] = "Nefarian",
		},
		["Thanagor"] = {
			["coin"] = 721,
			["lastUpdate"] = 1436923196,
			[3] = 1,
			["maxRested"] = 5400,
			["secondsPlayed"] = 5170,
			["faction"] = "Alliance",
			["name"] = "Thanagor",
			["level"] = 6,
			["rested"] = 0,
			["realm"] = "Nefarian",
		},
		["Haeldeus"] = {
			["coin"] = 237240,
			["lastUpdate"] = 1446412451,
			[3] = 1,
			["maxRested"] = 51000,
			["secondsPlayed"] = 147754,
			["faction"] = "Horde",
			["name"] = "Haeldeus",
			["level"] = 25,
			["rested"] = 27974,
			["realm"] = "Nefarian",
		},
	},
}
