
TitanSettings = {
	["Players"] = {
		["Syllix@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = 1,
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["ShowTooltipName"] = 1,
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["DisableRosterUpdates"] = "Titan Nil",
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowBattleground"] = 1,
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowHigher"] = "Titan Nil",
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = 0,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = 0,
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Ricky@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = "Titan Nil",
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = 1,
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["DisableRosterUpdates"] = "Titan Nil",
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["ShowTooltipName"] = 1,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Summoner"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowHigher"] = "Titan Nil",
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowBattleground"] = 1,
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = "Titan Nil",
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = "0.70s",
					["ShowLabelText"] = 1,
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Thanagor@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = 1,
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["ShowTooltipName"] = 1,
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["DisableRosterUpdates"] = "Titan Nil",
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowBattleground"] = 1,
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowHigher"] = "Titan Nil",
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = 0,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = 0,
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Synflix@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = "Titan Nil",
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["DisableRosterUpdates"] = "Titan Nil",
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["ShowTooltipName"] = 1,
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowHigher"] = "Titan Nil",
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowBattleground"] = 1,
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = 0,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = "1.43s",
					["ShowLabelText"] = 1,
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Synti@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = "Titan Nil",
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Volume",
					[5] = "UIScale",
					[6] = "Trans",
					[7] = "AutoHide",
					[8] = "HonorPlus",
					[9] = "Bag",
					[10] = "Money",
					[11] = "AuxAutoHide",
					[12] = "Repair",
					[13] = "ItemBonuses",
					[14] = "Clock",
					[15] = "Performance",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "AuxBar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "Bar",
					[15] = "Bar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["ShowTooltipName"] = 1,
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["DisableRosterUpdates"] = "Titan Nil",
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowBattleground"] = 1,
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowHigher"] = "Titan Nil",
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = 0,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = "1.23s",
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Haeldeus@Nefarian"] = {
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = "Titan Nil",
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
			["Plugins"] = {
				["Durability"] = {
					["inventory"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["iteminfodamaged"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowWarnings"] = "Titan Nil",
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["shownLeaders"] = {
					},
					["shownRanks"] = {
					},
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Experience"] = 1,
					["Health"] = 1,
					["Mode"] = 0,
					["Armor"] = 1,
					["Level"] = 1,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["TradeCooldown"] = {
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["NotifyEnable"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["hidemm"] = 1,
					["ShowIcon"] = 1,
					["ShowIconAlt"] = 0,
					["ShowText"] = 1,
					["chat"] = 1,
					["sound"] = 1,
					["new"] = 0,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["ShowAll"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["GroupBehavior"] = 1,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["Bag"] = {
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["CountProfBagSlots"] = "Titan Nil",
				},
				["Guild"] = {
					["ShowTooltipClass"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["ShowTooltipName"] = 1,
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipLevel"] = 1,
					["ShowTooltipRank"] = 1,
					["ShowIcon"] = 1,
					["DisableRosterUpdates"] = "Titan Nil",
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowBattleground"] = 1,
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowContinent"] = "Titan Nil",
					["ShowRaid"] = "Titan Nil",
					["ShowFaction"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowHigher"] = "Titan Nil",
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["AlternateDisplay"] = 0,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["ShowLabelText"] = 1,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowBarText"] = 1,
					["ShowPetName"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["IgnoreMultiRoll"] = 0,
					["HighlightParty"] = 0,
					["ListLength"] = 10,
					["ShowLabelText"] = 1,
					["Timeout"] = 20,
					["ShowWinner"] = 1,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = "0.59s",
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iDiamond"] = 0,
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowFPS"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = "Titan Nil",
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DBEST"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DFIVE"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["ShowLevel"] = "Titan Nil",
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
		},
		["Bärforceone@Nefarian"] = {
			["Plugins"] = {
				["Durability"] = {
					["iteminfodamaged"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["showallrepaircosts"] = "Titan Nil",
					["iteminfo"] = "Titan Nil",
					["showrepaircostintp"] = "Titan Nil",
					["ShowIcon"] = 1,
					["showinventoryintp"] = "Titan Nil",
					["showrepaircost10"] = "Titan Nil",
					["hideguy"] = 1,
					["ShowLabelText"] = 1,
					["showrepaircost20"] = "Titan Nil",
					["inventory"] = "Titan Nil",
					["showlowestitemintp"] = "Titan Nil",
					["showduraintp"] = 1,
					["showtotalduraintp"] = "Titan Nil",
					["showrepaircost"] = 1,
				},
				["Guild"] = {
					["ShowTooltipRank"] = 1,
					["FilterClasses"] = "Titan Nil",
					["DisableMouseOverUpdates"] = 1,
					["FilterMyZone"] = "Titan Nil",
					["SortByValue"] = "Titan Nil",
					["DisableRosterUpdates"] = "Titan Nil",
					["RosterUpdateTime"] = 300,
					["FilterMyLevel"] = "Titan Nil",
					["ShowTooltipZone"] = 1,
					["ShowTooltipNote"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowMenuOptions"] = 1,
					["ShowAdvancedMenus"] = 0,
					["ShowTooltipName"] = 1,
					["ShowTooltipClass"] = 1,
					["ShowIcon"] = 1,
					["ShowTooltipLevel"] = 1,
				},
				["DamageMeters"] = {
					["shownValues"] = {
					},
					["ShowIcon"] = 1,
					["shownRanks"] = {
					},
					["shownLeaders"] = {
					},
					["ShowLabelText"] = 1,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowZoneText"] = 1,
					["ShowCoordsOnMap"] = 1,
					["ShowLabelText"] = 1,
				},
				["BWP"] = {
					["ShowLabel"] = 1,
					["ShowIcon"] = 1,
				},
				["CritLine"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["TradeCooldown"] = {
					["NotifyEnable"] = 1,
					["ShowIcon"] = 1,
					["ShowEvergreen"] = "Titan Nil",
					["ShowOnlyCurrentRealm"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["Friends"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Tracker"] = {
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Skills"] = {
					["ShowIcon"] = 1,
					["ShowLevel"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Auctions"] = {
					["ShowExpiryTime"] = 1,
					["ShowEventTime"] = 1,
					["hideguy"] = 0,
					["ShowLabelText"] = 1,
					["ShowSmallButton"] = 0,
					["ShowIcon"] = 1,
					["RemainingTime"] = 1,
					["PlaySound"] = 0,
				},
				["CombatInfo"] = {
					["ShowCrit"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowStatLabel"] = "Titan Nil",
					["ShowBlock"] = "Titan Nil",
					["ShowDodge"] = "Titan Nil",
					["ShowParry"] = "Titan Nil",
				},
				["Aggro"] = {
					["ShowColoredText"] = 1,
					["RelocateTT_HP"] = 1,
					["AggroDetectPets"] = 0,
					["Sounds"] = 1,
					["ReportChans"] = {
					},
					["ReportTime"] = 0,
					["MoveableTT_HP"] = 0,
					["ReportFormat"] = 0,
					["ReportTypeCustomClasses"] = {
					},
					["HideFlashTT_HP"] = 0,
					["TankMode"] = 0,
					["DoReports"] = 0,
					["ShowLabelText"] = 1,
					["ReportTypeCustom"] = 0,
					["AggroDetect"] = 0,
					["ReportTimeSec"] = "Titan Nil",
					["ShowTT_HP"] = 1,
					["ReportType"] = 1,
				},
				["ModMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["WindFury"] = {
					["WF_OPT_DLAST"] = 1,
					["showIcon"] = 1,
					["WF_OPT_DEBUG"] = "Titan Nil",
					["WF_OPT_DFIVE"] = 1,
					["WF_OPT_DTEXT"] = 1,
					["WF_OPT_DBEST"] = 1,
				},
				["DamageMetersRight"] = {
					["ShowIcon"] = 1,
				},
				["Repair"] = {
					["ShowPercentage"] = "Titan Nil",
					["ShowColoredText"] = "Titan Nil",
					["ShowInventory"] = 1,
					["RepairInventory"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowItemName"] = "Titan Nil",
					["ShowUndamaged"] = "Titan Nil",
					["ShowPopup"] = "Titan Nil",
				},
				["PetXp"] = {
					["Stats"] = 0,
					["Loyalty"] = 1,
					["Food"] = 1,
					["Color"] = 0,
					["BarLevel"] = 0,
					["Health"] = 1,
					["Experience"] = 1,
					["Level"] = 1,
					["Armor"] = 1,
					["Mode"] = 0,
					["TrainingPoints"] = 0,
					["Damage"] = 1,
				},
				["Rider"] = {
					["ShowColoredText"] = "Titan Nil",
					["PlayerState"] = 1,
					["RiderItems"] = {
						[1] = "FeetSlot",
						[2] = "Trinket0Slot",
						[3] = "HandsSlot",
					},
					["ShowIcon"] = 1,
					["EquipItems"] = 1,
					["ShowLabelText"] = 1,
					["ShowState"] = 1,
				},
				["MacroMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["XPBar"] = {
					["StatusBar"] = 1,
					["XPFormat"] = 1,
					["ShowStatusBarText"] = 1,
				},
				["BuffReagent"] = {
					["MonitorCaption"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowColoredButton"] = "Titan Nil",
					["ShowWarnings"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Mail"] = {
					["total"] = 0,
					["compact"] = 1,
					["NoIconNoMail"] = 0,
					["ShowCount"] = 1,
					["new"] = 0,
					["ShowIcon"] = 1,
					["sound"] = 1,
					["chat"] = 1,
					["ShowText"] = 1,
					["ShowIconAlt"] = 0,
					["hidemm"] = 1,
				},
				["ModMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Quests"] = {
					["SortByLevel"] = "Titan Nil",
					["ShowRegular"] = "Titan Nil",
					["ShowPVP"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowRaid"] = "Titan Nil",
					["SortByTitle"] = "Titan Nil",
					["ShowElite"] = "Titan Nil",
					["QuestsWatched"] = {
					},
					["ClickBehavior"] = "Titan Nil",
					["ShowIncomplete"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowCompleted"] = "Titan Nil",
					["SortByLocation"] = 1,
					["GroupBehavior"] = 1,
					["ShowDungeon"] = "Titan Nil",
					["ShowAll"] = 1,
				},
				["Ammo"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Inn"] = {
					["ShowLabelText"] = 1,
				},
				["Bag"] = {
					["CountProfBagSlots"] = "Titan Nil",
					["CountShardBagSlots"] = "Titan Nil",
					["CountAmmoPouchSlots"] = "Titan Nil",
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowUsedSlots"] = 1,
					["ShowColoredText"] = 1,
				},
				["RoguePowder"] = {
					["CountBandages"] = 0,
					["ColoredText"] = 1,
					["ShowAvailableOnly"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["TRZ"] = {
					["ShowLower"] = "Titan Nil",
					["ShowColoredText"] = 1,
					["ShowHigher"] = "Titan Nil",
					["ShowLoc"] = 1,
					["ShowInstance"] = 1,
					["ShowLabelText"] = 1,
					["ShowMap"] = 1,
					["ShowBattleground"] = 1,
					["ShowRaid"] = "Titan Nil",
					["ShowCurInstance"] = 1,
					["ShowFaction"] = "Titan Nil",
					["ShowContinent"] = "Titan Nil",
				},
				["ItemDed"] = {
					["ShowChatFeedback"] = 1,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["ClassTracker"] = {
					["ButtonTextType"] = 1,
					["ShowLabelText"] = 1,
				},
				["HonorPlus"] = {
					["SortByHonor"] = 0,
					["Print_Bonus"] = 1,
					["ShowIcon"] = 1,
					["AutoRelease"] = 1,
					["AutoBGMap"] = 1,
					["AutoJoinBG"] = 1,
					["Tooltip"] = 1,
					["ShowLabelText"] = 1,
					["ScoreBoard_Kills"] = 1,
					["SortByKills"] = 1,
					["AlternateDisplay"] = 0,
					["UseCalculatedToday"] = 0,
					["ScoreBoard_ClassColorList"] = 1,
					["ScoreBoard_ClassColorSymbol"] = 0,
					["ScoreBoard_Opium"] = 1,
				},
				["PetInfo"] = {
					["ShowPetAttrb"] = 1,
					["ShowColoredText"] = 1,
					["ShowPetName"] = 1,
					["ShowBarText"] = 1,
					["ShowPetLevel"] = 1,
					["ShowLabelText"] = 1,
				},
				["RestPlus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["DisplayOnRightSide"] = 1,
					["Format"] = "12H",
				},
				["Roll"] = {
					["EraseTimedOutRolls"] = 0,
					["OnlyGoodRollsWin"] = 1,
					["ShowIcon"] = 1,
					["ReplaceBadRolls"] = 1,
					["ShowTimeOut"] = 1,
					["Timeout"] = 20,
					["HighlightParty"] = 0,
					["ShowWinner"] = 1,
					["ShowLabelText"] = 1,
					["IgnoreMultiRoll"] = 0,
					["ListLength"] = 10,
					["AnnouncePattern"] = "[Roll]: $aNo active rolls.$b$w won with a roll of $r. There were $n rolls.$c Invalid rolls were made by: $i",
					["AcceptGroupOnly"] = 0,
					["SortList"] = 0,
					["PerformedRoll"] = "1-100",
				},
				["LootType"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Performance"] = {
					["ShowColoredText"] = 1,
					["ShowMemory"] = 1,
					["ShowLatency"] = 1,
					["ShowLabelText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowFPS"] = 1,
				},
				["ZoneSpeed"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["ShowLastZone"] = 1,
					["LastZone"] = "0.67s",
					["ShowLabelText"] = 1,
				},
				["XP"] = {
					["ShowIcon"] = 1,
					["ShowXPPerHourSession"] = 1,
					["ShowLabelText"] = 1,
				},
				["SoulShardCounter"] = {
					["WarnThreshold"] = 1,
					["ShowIcon"] = 1,
					["WarnTimer"] = 60,
					["WarnWhenLow"] = 1,
					["ShowLabelText"] = 1,
				},
				["BGinfo"] = {
					["BGINFO_AutoJoin"] = 0,
					["BGINFO_AutoRes"] = 0,
					["ShowIcon"] = 1,
					["HideMinimap"] = "Titan Nil",
					["BGINFO_AutoRel"] = 0,
					["ShowLabelText"] = 1,
				},
				["SkinTracker"] = {
					["ShowIcon"] = 1,
					["iDragonscale"] = 0,
					["iDiamond"] = 0,
					["ShowColoredButton"] = "Titan Nil",
					["iStack"] = 0,
					["ShowLabelText"] = 1,
				},
				["XPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["Speed"] = {
					["ShowIcon"] = 1,
					["ShowTenth"] = "Titan Nil",
					["ShowLabelText"] = "Titan Nil",
				},
				["MacroMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["StanceSets"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["EmoteMenuRight"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["KTL"] = {
					["ShowLabelText"] = 1,
				},
				["EmoteMenu"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["CHKSTONE"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["AllPlayed"] = {
					["ShowIcon"] = 1,
					["ShowLevel"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["PvPStatus"] = {
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
				},
				["TitanRegen"] = {
					["ShowMPRegen"] = 1,
					["ShowColoredText"] = "Titan Nil",
					["ShowHPRegen"] = 1,
					["ShowPercentage"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["ReloadUI"] = {
					["ShowLabelText"] = 1,
				},
				["ItemBonuses"] = {
					["ShowColoredText"] = "Titan Nil",
					["ShowIcon"] = 1,
					["displaybonuses"] = {
					},
					["shortdisplay"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
				["Factions"] = {
					["ShowIcon"] = 1,
					["ShowBoth"] = "Titan Nil",
					["MonitorFaction"] = "Titan Nil",
					["ShowRaw"] = "Titan Nil",
					["ShowMonitor"] = "Titan Nil",
					["ShowLabelText"] = 1,
				},
			},
			["Panel"] = {
				["CastingBar"] = 1,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = "Titan Nil",
				["BothBars"] = 1,
				["DisableFont"] = "Titan Nil",
				["AutoHide"] = "Titan Nil",
				["VersionShown"] = 1,
				["AuxScreenAdjust"] = "Titan Nil",
				["AuxAutoHide"] = "Titan Nil",
				["FontScale"] = 1,
				["Buttons"] = {
					[1] = "Coords",
					[2] = "XP",
					[3] = "LootType",
					[4] = "Clock",
					[5] = "Volume",
					[6] = "UIScale",
					[7] = "Trans",
					[8] = "AutoHide",
					[9] = "HonorPlus",
					[10] = "Bag",
					[11] = "Money",
					[12] = "AuxAutoHide",
					[13] = "Repair",
					[14] = "ItemBonuses",
				},
				["DoubleBar"] = 1,
				["AuxButtonAlign"] = 1,
				["Transparency"] = 0.7,
				["Position"] = 1,
				["Location"] = {
					[1] = "Bar",
					[2] = "Bar",
					[3] = "Bar",
					[4] = "Bar",
					[5] = "Bar",
					[6] = "Bar",
					[7] = "Bar",
					[8] = "Bar",
					[9] = "AuxBar",
					[10] = "AuxBar",
					[11] = "AuxBar",
					[12] = "AuxBar",
					[13] = "AuxBar",
					[14] = "AuxBar",
				},
				["AuxDoubleBar"] = 1,
				["ToolTipsShown"] = 1,
			},
		},
	},
	["Version"] = "2.20.11200",
}
TITAN_HONORPLUS = {
	["Ricky|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 1,
		["todayhk"] = 0,
	},
	["Thanagor|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
	["Synti|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
	["Bärforceone|Nefarian"] = {
		["todaycp"] = 0,
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["log"] = {
		},
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
	["Syllix|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
	["Synflix|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
	["Haeldeus|Nefarian"] = {
		["log"] = {
		},
		["weekdk"] = 0,
		["todaydk"] = 0,
		["lastweek"] = 0,
		["yesterday2"] = 0,
		["todaycp"] = 0,
		["yesterday"] = 0,
		["todayb"] = 0,
		["todayd"] = 0,
		["todayhk"] = 0,
	},
}
TITAN_HONORPLUS_CHATINFO = {
	["Ricky"] = {
		["show"] = {
			[1] = "ChatFrame1",
		},
		["r"] = 0.878,
		["g"] = 0.792,
		["b"] = 0.039,
	},
	["Default"] = {
		["show"] = {
			[1] = "ChatFrame1",
		},
		["r"] = 0.878,
		["g"] = 0.792,
		["b"] = 0.039,
	},
}
ServerTimeOffsets = {
	["Nefarian"] = 0,
}
