
TITAN_ACWOptions = {
	["alarm3minute"] = 0,
	["snoozetime"] = 300,
	["alarm3text"] = "Weckruf Nachricht!",
	["offsetminute"] = 0,
	["alarm1text"] = "Weckruf Nachricht!",
	["alarm3hour"] = 0,
	["alarm1minute"] = 0,
	["locked"] = 1,
	["alarm1hour"] = 0,
	["offset"] = 0,
	["alarm2text"] = "Weckruf Nachricht!",
	["on"] = 1,
	["alarm2hour"] = 0,
	["mode"] = 1,
	["alarm1on"] = 0,
	["timeformat"] = 24,
	["alarm2minute"] = 0,
	["alarm3on"] = 0,
	["alarm2on"] = 0,
}
