
TWFS = {
	["Kürschnermesser"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Starke Angelrute"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_PROCS"] = 0,
	},
	["Verwitterter Stab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Dunkelholzstab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Primitive Handklinge"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["VERSION"] = "1.3",
	["Zimmermannshammer"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_PROCS"] = 0,
	},
	["Kesselrührstab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Klare Kristallrute"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Milizkriegshammer"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Entersäbel"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Stab des Kanalisierers"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Stab der Adligen"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Kampferprobter Hammer"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_PROCS"] = 0,
	},
	["Leystab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["none"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
	["Mystikerstab der Flusspfoten"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
	["Zwergischer Magierstab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["UPDATE"] = "1.3",
	["Abgenutzter Dolch"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Stilett"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Kupferaxt"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Gebogener Stab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Stab von Dar'Orahil"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
	},
	["Stab von Orgrimmar"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
	["Kupferdolch"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_PROCS"] = 0,
	},
	["Klinge der Geschicklichkeit"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
	["Verunstalteter Holzstab"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_BEST"] = 0,
	},
	["Steintomahawk"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
	["Primitiver Wanderstecken"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
		["WF_ALL_PROCS"] = 0,
	},
	["Stock des Ältesten"] = {
		["WF_ALL_HITS"] = 0,
		["WF_ALL_TOTAL"] = 0,
		["WF_ALL_BEST"] = 0,
		["WF_ALL_PROCS"] = 0,
		["WF_ALL_CRITS"] = 0,
		["WF_ALL_SHIT"] = 0,
	},
}
